
services:
  mariadb:
    image: mariadb
    container_name: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: always

 

  nginx:
    image: nginx
    container_name: nginx
    build: ./requirements/nginx
    env_file:
      - .env
    depends_on:
      - wordpress

    ports:
      - 443:443
    volumes:
      - wordpress:${WORDPRESS_PATH}
    networks:
      - inception
    restart: on-failure

  
  wordpress:
    image: wordpress
    container_name: wordpress
    build: ./requirements/wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wordpress:${WORDPRESS_PATH}
    networks:
      - inception
    restart: on-failure

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  mariadb:  
    driver: local
    driver_opts:
      type: none
      device: /home/kammi/data/mysql
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/kammi/data/wordpress
      o: bind
 

