
services:
  mariadb:
    image: mariadb
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    build: 
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    restart: always

  

  nginx:
    container_name: nginx
    volumes:
      - wordpress:$WORDPRESS_PATH
    networks:
      - inception
    depends_on: 
      - wordpress
    build: 
      context: ./requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "443:443"
    restart: on-failure

  
  wordpress:
    container_name: wordpress
    volumes:
      - wordpress:$WORDPRESS_PATH
    networks:
      - inception
    build: 
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    env_file: .env
    restart: on-failure

networks:
  inception:
    driver: bridge

volumes:
  mariadb_data:
  wordpress:
 